// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jivzhyyecftqdgpezzry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdnpoeXllY2Z0cWRncGV6enJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjk0NTgsImV4cCI6MjA2MDY0NTQ1OH0.8D5Ci8A6g9Gyiq0GMKmz8NqAe4lRZDXvc56h8-HsJLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);